const cards = document.querySelector('#cards');
const dialog = document.querySelector('#recipe-dialog');
const number = n => Number(n.toFixed(1)).toString();
const halfMacros = r => `<div class="macro-summary" aria-label="Estimated nutrition per half batch"><span><strong>${Math.round(r.mac[0]/2)}</strong><small>kcal</small></span><span><strong>${number(r.mac[1]/2)} g</strong><small>protein</small></span><span><strong>${number(r.mac[2]/2)} g</strong><small>carbs</small></span><span><strong>${number(r.mac[3]/2)} g</strong><small>fat</small></span></div><p class="macro-caption">Estimated per ½ batch · optional extras excluded</p>`;
const renderCard = r => `<article class="card" style="--accent:${r.color}"><div class="card-top"><span>${r.kind}</span><b>${String(recipes.indexOf(r)+1).padStart(2,'0')}</b></div><div class="card-body"><h3>${r.title}</h3><p class="card-description">${r.desc}</p><div class="card-nutrition">${halfMacros(r)}</div><button data-recipe="${r.id}" aria-haspopup="dialog" aria-label="View ${r.title} recipe">View recipe <span aria-hidden="true">↗</span></button></div></article>`;
cards.innerHTML = recipes.filter(r=>!r.healthy).map(renderCard).join('');
document.querySelector('#healthy-cards').innerHTML = recipes.filter(r=>r.healthy&&!r.plant).map(renderCard).join('');
document.querySelector('#plant-cards').innerHTML = recipes.filter(r=>r.plant).map(renderCard).join('');
const list = (items,tag) => `<${tag}>${items.map(x=>`<li>${x}</li>`).join('')}</${tag}>`;
function mixinIdeas(r) {
 return `<section class="mixin-section"><h3>Make it your own</h3><p>Choose one idea for <strong>½ batch</strong>; double it for a whole batch. These are optional extras, not required ingredients.</p><div class="mixin-grid">${r.mixins.map(m=>`<article class="mixin-idea"><span class="mixin-method">${m.method==='mix'?'MIX-IN or topping':'Topping only'}</span><h4>${m.name}</h4><p>${m.portion}</p><strong>≈ +${m.kcal} kcal per ½ batch</strong></article>`).join('')}</div><details class="mixin-help"><summary>How to add these extras</summary>${r.kind==='Sorbet'?'<p>For this sorbet, spoon these toppings over your served scoop; no extra machine cycle is needed.</p>':'<p>For a MIX-IN option, first process the base using its recipe program. Make a roughly 4 cm wide hole down through the processed portion, add the pieces, and select MIX-IN using the same TOP, BOTTOM or FULL zone. Chop hard chocolate and nuts small before adding.</p><p>You can also sprinkle any crunchy option on top to keep its crunch. Add toppings only after all processing. Keep fresh fruit, syrups and sauces on the served scoop rather than putting them through MIX-IN; they can soften the texture.</p>'}<p>Leave space below SCOOPABLE MAX FILL. Extra calories are rough ingredient estimates; brands vary, and optional extras also change protein, carbs and fat. The base macros below include everything in the ingredient list, including any reserved biscuits, chocolate or nuts, but exclude these optional ideas.</p><a href="https://ninjakitchenapac.zendesk.com/hc/en-au/articles/5369888572303-Product-Setup-How-to-Use" target="_blank" rel="noopener">Ninja’s mix-in guidance</a></details></section>`;
}
function openRecipe(id) {
 const r=recipes.find(x=>x.id===id); if(!r)return;
 document.querySelector('#recipe-content').innerHTML=`<p class="eyebrow">DESSERTS / ${r.healthy?'HEALTHY VERSIONS / ':''}${r.kind.toUpperCase()}</p><h2 id="recipe-title">${r.title}</h2><p class="description">${r.desc}</p><p class="small">1 batch · 2 suggested servings · Freeze at least 24 hours · CREAMi Deluxe</p><div class="recipe-macros">${halfMacros(r)}</div><div class="recipe-layout"><section><h3>Ingredients</h3>${list(r.ingredients,'ul')}</section><section><h3>Prepare & freeze</h3>${list(r.prep,'ol')}<h3>Spin & serve</h3>${list(r.spin,'ol')}</section></div>${mixinIdeas(r)}<section><h3>Store & enjoy again</h3>${list(r.storage,'ol')}</section><section class="nutrition"><b>Estimated nutrition</b><table><thead><tr><th scope="col">Amount</th><th scope="col">kcal</th><th scope="col">Protein</th><th scope="col">Carbs</th><th scope="col">Fat</th></tr></thead><tbody>${[2,1].map(div=>`<tr><th scope="row">${div===2?'½ batch':'Whole batch'}</th>${r.mac.map((n,i)=>`<td>${i?number(n/div)+' g':Math.round(n/div)}</td>`).join('')}</tr>`).join('')}</tbody></table><p>Estimates for the ingredient list, including reserved toppings. Optional ideas above are additional. Exact product labels, brands and rounding affect totals. A batch does not necessarily fill a 700 ml tub.</p></section><p class="caveat">${r.note}</p><p class="caveat">Homemade starting recipe; not personally kitchen-tested. Keep below SCOOPABLE MAX FILL and follow your machine’s manual.</p>`;
 dialog.showModal(); dialog.scrollTop=0;
}
document.querySelector('#recipes').addEventListener('click',e=>{const b=e.target.closest('[data-recipe]');if(b)openRecipe(b.dataset.recipe)});
document.querySelector('.close').addEventListener('click',()=>dialog.close());
dialog.addEventListener('click',e=>{if(e.target===dialog){const b=dialog.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)dialog.close()}});
